bucket4j:
  enabled: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
  rate-limits:
    limits:
      - method: GET
        capacity: ${GET_RATE_LIMITER_CAPACITY:200}
        refill:
          tokens: ${GET_RATE_LIMITER_REFILL:200}
          period: ${GET_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${GET_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: POST
        capacity: ${POST_RATE_LIMITER_CAPACITY:10}
        refill:
          tokens: ${POST_RATE_LIMITER_REFILL:10}
          period: ${POST_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${POST_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: PUT
        capacity: ${PUT_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${PUT_RATE_LIMITER_REFILL:15}
          period: ${PUT_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${PUT_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: PATCH
        capacity: ${PATCH_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${PATCH_RATE_LIMITER_REFILL:15}
          period: ${PATCH_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${PATCH_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: DELETE
        capacity: ${DELETE_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${DELETE_RATE_LIMITER_REFILL:15}
          period: ${DELETE_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${DELETE_RATE_LIMITER_REFILL_UNIT:MINUTES}
resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: ${RESILIENCE4J_DEFAULT_RATE_LIMIT:10}
        limit-refresh-period: ${RESILIENCE4J_DEFAULT_RATE_REFRESH_PERIOD:1s}
        timeout-duration: ${RESILIENCE4J_DEFAULT_RATE_TIMEOUT:500ms}
        register-health-indicator: true
        event-consumer-buffer-size: 100
    instances:
      global:
        base-config: default
        limit-for-period: ${RESILIENCE4J_GLOBAL_RATE_LIMIT:5000}
        limit-refresh-period: ${RESILIENCE4J_GLOBAL_RATE_REFRESH:1s}
        timeout-duration: ${RESILIENCE4J_GLOBAL_RATE_TIMEOUT:100ms}
        register-health-indicator: true